### ISSUE TITLE
"if statement" - looks like a bug.

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/staq#15] opened 2020-05-09 20:06 UTC
This snippet (Let's call it input.qasm.) reveals a problem.

> OPENQASM 2.0;
> include "qelib1.inc";
> 
> qreg q[3];
> qreg qqq[1];
> 
> creg c[3];
> 
> measure q -> c;
> 
> if(c==1) x qqq;

When I run this:

`./staq   -o output.qasm   input.qasm`

It will produce this output:

> OPENQASM 2.0;
> include "qelib1.inc";
> 
> qreg q[3];
> qreg qqq[1];
> creg c[3];
> measure q[0] -> c[0];
> measure q[1] -> c[1];
> measure q[2] -> c[2];
> x qqq[0];

The output is functionally different from the input because the `if `statement is gone.

If the `if` statement takes this form 

`if(c==1) x qqq[0]; `

everything will work as expected.

**Comment by meamy** [comment] 2020-05-12 20:24
Thanks for the bug report -- it was caused by an error in some of the visitor logic. It should be fixed now.

**Closed by meamy** 2020-05-12 20:24 UTC
